
-- Script de Remoção das Tabelas (apaga.sql)

DROP TABLE FATO_AVALIACAO_ENTREGA CASCADE CONSTRAINTS;
DROP TABLE DIM_TEMPO CASCADE CONSTRAINTS;
DROP TABLE DIM_PRODUTO CASCADE CONSTRAINTS;
DROP TABLE DIM_SUBCATEGORIA CASCADE CONSTRAINTS;
DROP TABLE DIM_CATEGORIA CASCADE CONSTRAINTS;
DROP TABLE DIM_CENTRO_DISTRIBUICAO CASCADE CONSTRAINTS;
DROP TABLE DIM_CLIENTE CASCADE CONSTRAINTS;
DROP TABLE DIM_LOCAL CASCADE CONSTRAINTS;
DROP TABLE DIM_ESTADO CASCADE CONSTRAINTS;
DROP TABLE DIM_REGIAO CASCADE CONSTRAINTS;
