
-- Script de Criação das Tabelas (cria.sql)

CREATE TABLE DIM_REGIAO (
    CD_REGIAO NUMBER(5) PRIMARY KEY,
    NOME_REGIAO VARCHAR2(50)
);

CREATE TABLE DIM_ESTADO (
    CD_ESTADO VARCHAR2(2) PRIMARY KEY,
    DIM_ESTADO_ID NUMBER,
    NOME_ESTADO VARCHAR2(45),
    CD_REGIAO NUMBER(5),
    FOREIGN KEY (CD_REGIAO) REFERENCES DIM_REGIAO(CD_REGIAO)
);

CREATE TABLE DIM_LOCAL (
    CD_LOCAL NUMBER(25) PRIMARY KEY,
    CIDADE VARCHAR2(100),
    BAIRRO VARCHAR2(100),
    CD_ESTADO VARCHAR2(2),
    FOREIGN KEY (CD_ESTADO) REFERENCES DIM_ESTADO(CD_ESTADO)
);

CREATE TABLE DIM_CLIENTE (
    CD_CLIENTE VARCHAR2(20) PRIMARY KEY,
    NOME_CLIENTE VARCHAR2(100),
    CD_LOCALIZACAO NUMBER(25),
    FOREIGN KEY (CD_LOCALIZACAO) REFERENCES DIM_LOCAL(CD_LOCAL)
);

CREATE TABLE DIM_CENTRO_DISTRIBUICAO (
    CD_CD_DISTRIBUICAO VARCHAR2(20) PRIMARY KEY,
    NOME_CD VARCHAR2(100),
    CD_LOCAL NUMBER(5),
    FOREIGN KEY (CD_LOCAL) REFERENCES DIM_LOCAL(CD_LOCAL)
);

CREATE TABLE DIM_CATEGORIA (
    CD_CATEGORIA NUMBER(25) PRIMARY KEY,
    NOME_CATEGORIA VARCHAR2(100)
);

CREATE TABLE DIM_SUBCATEGORIA (
    CD_SUBCATEGORIA NUMBER(5) PRIMARY KEY,
    NOME_SUBCATEGORIA VARCHAR2(100),
    CD_CATEGORIA NUMBER(25),
    FOREIGN KEY (CD_CATEGORIA) REFERENCES DIM_CATEGORIA(CD_CATEGORIA)
);

CREATE TABLE DIM_PRODUTO (
    CD_PRODUTO VARCHAR2(20) PRIMARY KEY,
    NOME_PRODUTO VARCHAR2(100),
    CD_SUBCATEGORIA NUMBER(5),
    FOREIGN KEY (CD_SUBCATEGORIA) REFERENCES DIM_SUBCATEGORIA(CD_SUBCATEGORIA)
);

CREATE TABLE DIM_TEMPO (
    ID_TEMPO NUMBER(6) PRIMARY KEY,
    DATA_COMPLETA DATE,
    DIA NUMBER(2),
    MES NUMBER(2),
    ANO NUMBER(4),
    DIA_SEMANA VARCHAR2(20),
    TRIMESTRE NUMBER(1),
    SEMANA_ANO NUMBER(6)
);

CREATE TABLE FATO_AVALIACAO_ENTREGA (
    ID_FATO NUMBER(4) PRIMARY KEY,
    DIM_CLIENTE_CD_CLIENTE VARCHAR2(20),
    DIM_CENTRO_DISTRIBUICAO_CD_CD_DISTRIBUICAO VARCHAR2(20),
    DIM_PRODUTO_CD_PRODUTO VARCHAR2(20),
    DIM_TEMPO_ID_TEMPO NUMBER(6),
    DIM_TEMPO_ID_TEMPO2 NUMBER(6),
    DIM_TEMPO_ID_TEMPO3 NUMBER(6),
    DIM_TEMPO_ID_TEMPO4 NUMBER(6),
    NR_PEDIDO VARCHAR2(20),
    NR_ITEM NUMBER(5),
    NOTA_EMBALAGEM NUMBER(2,1),
    NOTA_PONTUALIDADE NUMBER(2,1),
    NOTA_CORTESIA NUMBER(2,1),
    TEMPO_ENTREGA_MIN NUMBER(6),
    QTD_ENTREGA_REALIZADA NUMBER,
    QTD_ENTREGA_PLANEJADA NUMBER,
    VL_TOTAL_ITEM NUMBER(10,2),
    FOREIGN KEY (DIM_CLIENTE_CD_CLIENTE) REFERENCES DIM_CLIENTE(CD_CLIENTE),
    FOREIGN KEY (DIM_CENTRO_DISTRIBUICAO_CD_CD_DISTRIBUICAO) REFERENCES DIM_CENTRO_DISTRIBUICAO(CD_CD_DISTRIBUICAO),
    FOREIGN KEY (DIM_PRODUTO_CD_PRODUTO) REFERENCES DIM_PRODUTO(CD_PRODUTO),
    FOREIGN KEY (DIM_TEMPO_ID_TEMPO) REFERENCES DIM_TEMPO(ID_TEMPO),
    FOREIGN KEY (DIM_TEMPO_ID_TEMPO2) REFERENCES DIM_TEMPO(ID_TEMPO),
    FOREIGN KEY (DIM_TEMPO_ID_TEMPO3) REFERENCES DIM_TEMPO(ID_TEMPO),
    FOREIGN KEY (DIM_TEMPO_ID_TEMPO4) REFERENCES DIM_TEMPO(ID_TEMPO)
);
